"use client";
import { useState,useMemo,useCallback } from "react";
import { useRouter,useSearchParams } from "next/navigation";
import dynamic from "next/dynamic";
import { Search, SlidersHorizontal, Map, LayoutGrid, X } from "lucide-react";
import { themes,type Region } from "@/lib/types";
import { RegionCard } from "./region-card";
const RegionMap=dynamic(()=>import("./region-map"),{ssr:false,loading:()=> <div className="map-loading">지도를 불러오고 있어요…</div>});
export function Explorer({regions,mapRegions,visitorDataAsOf}:{regions:Region[];mapRegions:Region[];visitorDataAsOf?:string}){
 const router=useRouter(),params=useSearchParams();const q=params.get("q")??"",theme=params.get("theme")??"",area=params.get("area")??"",policy=params.get("policy")??"";
 const [view,setView]=useState<"grid"|"map">("grid");const [search,setSearch]=useState(q);
 const [limit,setLimit]=useState(12);
 const matches=useCallback((r:Region)=>(!q||r.name.includes(q)||r.areaName.includes(q))&&(!theme||r.theme===theme)&&(!area||r.areaCode===area)&&(!policy||(policy==="HALF_PRICE"?r.halfPrice:r.populationStatus===policy)),[q,theme,area,policy]);
 const visible=useMemo(()=>regions.filter(matches),[regions,matches]);const visibleMap=useMemo(()=>mapRegions.filter(matches),[mapRegions,matches]);
 const shown=visible.slice(0,limit);
 function update(key:string,value:string){const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);router.replace(`/explore?${next}`,{scroll:false});}
 const areas=Array.from(new globalThis.Map(regions.map(r=>[r.areaCode,r.areaName])).entries());
 return <><div className="explore-controls"><form onSubmit={e=>{e.preventDefault();update("q",search);}} className="search-box"><Search size={18}/><input aria-label="지역 검색" value={search} onChange={e=>setSearch(e.target.value)} placeholder="어느 동네가 궁금하세요?"/><button type="submit">검색</button></form><label className="area-filter"><SlidersHorizontal size={16}/><select aria-label="시도 선택" value={area} onChange={e=>update("area",e.target.value)}><option value="">모든 시도</option>{areas.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></div><div className="theme-tabs" aria-label="여행 테마">{themes.map(t=><button disabled={!!t.id&&!regions.some(r=>r.theme===t.id)} title={t.id&&!regions.some(r=>r.theme===t.id)?"테마별 지역을 준비 중입니다.":undefined} key={t.id} onClick={()=>update("theme",t.id)} aria-pressed={theme===t.id} className={theme===t.id?"selected":""}>{t.name}{t.id&&!regions.some(r=>r.theme===t.id)?" · 준비 중":""}</button>)}</div><div className="policy-tabs" aria-label="지역 정책 필터">{[{id:"DECLINING",name:"인구감소지역",count:89},{id:"INTEREST",name:"관심지역",count:18},{id:"HALF_PRICE",name:"반값여행",count:25}].map(t=><button key={t.id} onClick={()=>update("policy",policy===t.id?"":t.id)} aria-pressed={policy===t.id}>{t.name} <small>{t.count}</small></button>)}</div><div className="results-heading"><p><strong>{visible.length}개</strong> 지역 <span> · 공식 시군구 코드 기준</span></p><div className="view-toggle"><button aria-label="목록으로 보기" aria-pressed={view==="grid"} onClick={()=>setView("grid")}><LayoutGrid size={18}/></button><button aria-label="지도로 보기" aria-pressed={view==="map"} onClick={()=>setView("map")}><Map size={18}/></button></div></div>{visible.length===0?<div className="empty-state"><Search size={30}/><h2>아직 발견하지 못한 동네예요</h2><p>다른 지역명이나 테마로 찾아보세요.</p><button className="button" onClick={()=>{setSearch("");router.replace("/explore");}}><X size={16}/> 필터 초기화</button></div>:<>{view==="map"&&<><RegionMap regions={visibleMap}/><p className="muted small">서비스 지역 기준 경계(2025.12) · 회색은 방문량 자료 없음 · 색이 진할수록 방문량 기준 숨은 점수가 높습니다.{visitorDataAsOf&&` 방문 데이터 기준일 ${visitorDataAsOf}.`} 경계 출처: 통계청 SGIS·vuski/admdongkor, CC BY 4.0.</p></>}<div className="card-grid">{shown.map((r,i)=><RegionCard key={r.code} region={r} index={i}/>)}</div>{shown.length<visible.length&&<button className="button more-regions" onClick={()=>setLimit(v=>v+24)}>지역 더 보기 ({shown.length}/{visible.length})</button>}</>}</>;
}
