"use client";
import {useEffect,useRef,useState} from "react";
import * as maplibregl from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";
import type {Region} from "@/lib/types";
import {useRouter} from "next/navigation";
export default function RegionMap({regions}:{regions:Region[]}){
 const el=useRef<HTMLDivElement>(null);const [failed,setFailed]=useState(false);const router=useRouter();
 useEffect(()=>{if(!el.current)return;let map:maplibregl.Map|undefined;
 try{map=new maplibregl.Map({container:el.current,center:[127.8,36.2],zoom:5.65,minZoom:5,maxZoom:10,style:{version:8,sources:{},layers:[{id:"background",type:"background",paint:{"background-color":"#e9ede2"}}]}});
 map.addControl(new maplibregl.NavigationControl(),"top-right");map.on("error",()=>setFailed(true));
 map.on("load",async()=>{try{const response=await fetch("/data/korea-sgg.json");if(!response.ok)throw Error();const geo=await response.json() as GeoJSON.FeatureCollection;const byCode=new globalThis.Map(regions.map(r=>[r.code,r]));geo.features=geo.features.filter(f=>byCode.has(String(f.properties?.sgg))).map(f=>{const r=byCode.get(String(f.properties?.sgg))!;return {...f,properties:{...f.properties,name:r.name,areaName:r.areaName,hiddenScore:r.hiddenScore??0,populationStatus:r.populationStatus,halfPrice:r.halfPrice}}});map!.addSource("regions",{type:"geojson",data:geo,generateId:true});map!.addLayer({id:"region-fill",type:"fill",source:"regions",paint:{"fill-color":["interpolate",["linear"],["get","hiddenScore"],0,"#dfe6d8",50,"#88a77f",100,"#315b40"],"fill-opacity":.88}});map!.addLayer({id:"region-line",type:"line",source:"regions",paint:{"line-color":"#f7f5ed","line-width":["case",["boolean",["feature-state","hover"],false],2.4,.65]}});let hovered:string|number|undefined;map!.on("mousemove","region-fill",e=>{map!.getCanvas().style.cursor="pointer";if(hovered!==undefined)map!.setFeatureState({source:"regions",id:hovered},{hover:false});hovered=e.features?.[0]?.id;if(hovered!==undefined)map!.setFeatureState({source:"regions",id:hovered},{hover:true});});map!.on("mouseleave","region-fill",()=>{map!.getCanvas().style.cursor="";if(hovered!==undefined)map!.setFeatureState({source:"regions",id:hovered},{hover:false});hovered=undefined;});map!.on("click","region-fill",e=>{const code=String(e.features?.[0]?.properties?.sgg??"");if(/^\d{5}$/.test(code))router.push(`/regions/${code}`);});const popup=new maplibregl.Popup({closeButton:false,closeOnClick:false});map!.on("mouseenter","region-fill",e=>{const p=e.features?.[0]?.properties;if(!p)return;const tags=[p.populationStatus==="DECLINING"?"인구감소지역":p.populationStatus==="INTEREST"?"관심지역":"",p.halfPrice?"반값여행":""].filter(Boolean).join(" · ");popup.setLngLat(e.lngLat).setHTML(`<strong>${p.areaName} ${p.name}</strong><small>숨은 점수 ${p.hiddenScore ?? "자료 없음"}${tags?`<br>${tags}`:""}</small>`).addTo(map!);});map!.on("mouseleave","region-fill",()=>popup.remove());}catch{setFailed(true);}});
 }catch{queueMicrotask(()=>setFailed(true));}return()=>map?.remove();},[regions,router]);
 return <div className="map-shell"><div ref={el} className="region-map" aria-label="지역 위치 지도"/>{failed&&<p className="map-warning" role="status">지도를 표시하지 못했습니다. 아래 지역 목록을 이용해 주세요.</p>}</div>;
}
