import Link from "next/link";
import { notFound } from "next/navigation";
import type {Metadata} from "next";
import { ArrowLeft,ArrowUpRight,MapPin,CalendarDays,Info } from "lucide-react";
import { getRegion,getPhotos,getPlaces,getCrowd } from "@/lib/api";
import {safeTourImage,themeName} from "@/lib/types";
import {PhotoImage} from "@/components/photo";
import {Reactions} from "@/components/reactions";
import {PhotoGallery} from "@/components/photo-gallery";
export async function generateMetadata({params}:{params:Promise<{code:string}>}):Promise<Metadata>{const r=await getRegion((await params).code);return {title:r?`${r.name}, ${r.tagline}`:"지역 여행",description:r?.tagline,openGraph:{images:r?.heroPhoto?[{url:r.heroPhoto.url,alt:r.heroPhoto.title}]:[]}};}
export default async function RegionPage({params}:{params:Promise<{code:string}>}){
 const {code}=await params;if(!/^\d{5}$/.test(code))notFound();const regionBase=await getRegion(code,false);if(!regionBase)notFound();
 const [photos,places,crowd]=await Promise.all([getPhotos(code),getPlaces(code),getCrowd(code)]);
 const region={...regionBase,heroPhoto:photos?.items[0]??null};
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()).replaceAll("-","");
 const forecasts=(crowd?.items??[]).filter(d=>/^\d{8}$/.test(d.baseYmd)&&d.baseYmd>=today&&d.cnctrRate!==""&&Number.isFinite(Number(d.cnctrRate))).sort((a,b)=>a.baseYmd.localeCompare(b.baseYmd));
 const quietDays=[...forecasts].sort((a,b)=>Number(a.cnctrRate)-Number(b.cnctrRate)).slice(0,3);
 const min=forecasts.length?Math.min(...forecasts.map(d=>Number(d.cnctrRate))):0;
 return <main id="main" className="detail-main"><div className="wrap detail-top"><Link className="back-link" href="/explore"><ArrowLeft size={16}/> 지역 둘러보기</Link><span className="eyebrow">{themeName(region.theme)}</span></div><section className="detail-hero wrap"><div className="detail-title"><p className="eyebrow"><MapPin size={14}/>{region.areaName}</p><h1>{region.name}</h1><p>{region.tagline}</p><Reactions code={code} name={region.name}/></div><div className="detail-photo"><PhotoImage src={region.heroPhoto?.url} alt={region.heroPhoto?.title??region.name} priority/><div className="photo-caption">{region.heroPhoto?.title}<span>{region.heroPhoto?.source} · {region.heroPhoto?.photographer||"촬영자 정보 없음"}</span></div></div></section>
 <nav className="section-nav wrap" aria-label="지역 상세 섹션"><a href="#places">함께 가볼 곳</a><a href="#photos">사진으로 산책</a><a href="#quiet">한적한 날짜</a><a href="#data">데이터 이야기</a></nav>
 <section id="places" className="wrap detail-section"><div className="section-heading"><div><p className="eyebrow">TAKE A LITTLE DETOUR</p><h2>발길 닿는 곳마다.</h2></div><span className="muted small">출처: ⓒ한국관광공사 · 실시간 조회</span></div><div className="place-grid">{places?.items.map(p=><article className="place-card" key={p.contentid}><div className="place-image"><PhotoImage src={safeTourImage(p.firstimage)} alt={p.title}/></div><div><h3>{p.title}</h3><p><MapPin size={13}/>{p.addr1}</p><a href={`https://map.naver.com/p/search/${encodeURIComponent(p.title+" "+region.name)}`} target="_blank" rel="noopener noreferrer">지도에서 보기 <ArrowUpRight size={14}/></a><small>출처: ⓒ한국관광공사 · {p.cpyrhtDivCd||"이용조건 확인 필요"}</small></div></article>)}</div>{!places?.items.length&&<p className="empty-inline">실시간 관광정보가 없거나 연결이 원활하지 않습니다.</p>}</section>
 <section id="photos" className="wrap detail-section"><div className="section-heading"><div><p className="eyebrow">A WALK THROUGH PHOTOGRAPHS</p><h2>한 장씩, 동네 산책.</h2></div><span className="muted small">실시간으로 확인한 사진만 보여드려요.</span></div><PhotoGallery photos={photos?.items??[]}/><p className="source-note">출처: ⓒ한국관광콘텐츠랩 · 이용조건은 <a href="https://korean.visitkorea.or.kr/photogallery/main.do" target="_blank" rel="noopener noreferrer">원문에서 확인</a>해 주세요.</p></section>
 {quietDays.length>0&&<div className="wrap notice"><strong>여유로운 여행 추천일</strong><p>{quietDays.map(d=>`${d.baseYmd.slice(4,6)}월 ${d.baseYmd.slice(6)}일 (${Number(d.cnctrRate).toFixed(1)})`).join(" · ")}</p>{crowd?.fetchedAt&&<small>실시간 조회: {new Date(crowd.fetchedAt).toLocaleString("ko-KR",{timeZone:"Asia/Seoul"})}</small>}</div>}
 <section id="quiet" className="wrap detail-section quiet-section"><div><p className="eyebrow"><CalendarDays size={15}/> TIMING MAKES A DIFFERENCE</p><h2>조금 더 여유로운 날.</h2><p>{region.anchorPlace?`${region.anchorPlace}의`:"이 지역에서 지원되는 관광지의"} 집중률 예측이에요.<br/>숫자가 낮은 날을 골라 천천히 둘러보세요.</p><span className="source-note">출처: ⓒ한국관광공사 · 상대적 예측값이며 실제 방문객 수가 아닙니다.<br/>당일 현장 상황과 다를 수 있어요.</span></div><div>{forecasts.length?<><div className="calendar-grid">{forecasts.map(d=><div key={`${d.baseYmd}-${d.tAtsNm}`} className={`calendar-cell ${Number(d.cnctrRate)===min?"quietest":""}`}><span>{d.baseYmd.slice(4,6)}.{d.baseYmd.slice(6)}</span><strong>{Number(d.cnctrRate).toFixed(1)}</strong></div>)}</div><p className="muted small">진한 초록: 조회 기간 중 가장 낮은 집중률 · 출처: ⓒ한국관광공사</p></>:<div className="empty-inline"><CalendarDays size={28}/><p>이 지역은 집중률 API 지원 결과가 없거나 연결이 원활하지 않습니다.<br/>사진과 주변 장소를 먼저 둘러보세요.</p></div>}</div></section>
 <section id="data" className="wrap data-note"><Info size={23}/><div><h3>여행의 근거도, 투명하게.</h3><p>전국 시군구를 공식 코드로 탐색하고, 사진·관광지·집중률은 화면을 열 때 공공 API에서 실시간으로 조회합니다. 에디터 추천 8개 지역은 검증된 중심 좌표와 소개 문구를 추가로 제공합니다.</p><Link href="/methodology">출처와 선정 방식 살펴보기 <ArrowUpRight size={15}/></Link></div></section></main>;
}
