import Link from "next/link";
import { notFound } from "next/navigation";
import type {Metadata} from "next";
import { ArrowLeft,ArrowUpRight,MapPin,CalendarDays,Info } from "lucide-react";
import { getRegion,getPhotos,getPlaces,getCrowd } from "@/lib/api";
import {safeTourImage,themeName} from "@/lib/types";
import {PhotoImage} from "@/components/photo";
import {Reactions} from "@/components/reactions";
export async function generateMetadata({params}:{params:Promise<{code:string}>}):Promise<Metadata>{const r=await getRegion((await params).code);return {title:r?`${r.name}, ${r.tagline}`:"지역 여행",description:r?.tagline,openGraph:{images:r?.heroPhoto?[{url:r.heroPhoto.url,alt:r.heroPhoto.title}]:[]}};}
export default async function RegionPage({params}:{params:Promise<{code:string}>}){
 const {code}=await params;if(!/^\d{5}$/.test(code))notFound();const region=await getRegion(code);if(!region)notFound();
 const [photos,places,crowd]=await Promise.all([getPhotos(code),getPlaces(code),getCrowd(code)]);
 const forecasts=(crowd?.items??[]).filter(d=>/^\d{8}$/.test(d.baseYmd)&&Number.isFinite(Number(d.cnctrRate))).sort((a,b)=>a.baseYmd.localeCompare(b.baseYmd));
 const min=forecasts.length?Math.min(...forecasts.map(d=>Number(d.cnctrRate))):0;
 return <main id="main" className="detail-main"><div className="wrap detail-top"><Link className="back-link" href="/explore"><ArrowLeft size={16}/> 지역 둘러보기</Link><span className="eyebrow">{themeName(region.theme)}</span></div><section className="detail-hero wrap"><div className="detail-title"><p className="eyebrow"><MapPin size={14}/>{region.areaName}</p><h1>{region.name}</h1><p>{region.tagline}</p><Reactions code={code} name={region.name}/></div><div className="detail-photo"><PhotoImage src={region.heroPhoto?.url} alt={region.heroPhoto?.title??region.name} priority/><div className="photo-caption">{region.heroPhoto?.title}<span>© {region.heroPhoto?.photographer||"한국관광공사"}</span></div></div></section>
 <nav className="section-nav wrap" aria-label="지역 상세 섹션"><a href="#places">함께 가볼 곳</a><a href="#photos">사진으로 산책</a><a href="#quiet">한적한 날짜</a><a href="#data">데이터 이야기</a></nav>
 <section id="places" className="wrap detail-section"><div className="section-heading"><div><p className="eyebrow">TAKE A LITTLE DETOUR</p><h2>발길 닿는 곳마다.</h2></div><span className="muted small">한국관광공사 지역 기반 관광정보</span></div><div className="place-grid">{places?.items.map(p=><article className="place-card" key={p.contentid}><div className="place-image"><PhotoImage src={safeTourImage(p.firstimage)} alt={p.title}/></div><div><h3>{p.title}</h3><p><MapPin size={13}/>{p.addr1}</p><a href={`https://map.naver.com/p/search/${encodeURIComponent(p.title+" "+region.name)}`} target="_blank" rel="noopener noreferrer">지도에서 보기 <ArrowUpRight size={14}/></a><small>사진 © 한국관광공사 · {p.cpyrhtDivCd||"출처 확인 필요"}</small></div></article>)}</div>{!places?.items.length&&<p className="empty-inline">이 동네의 장소 정보를 준비하고 있어요.</p>}</section>
 <section id="photos" className="wrap detail-section"><div className="section-heading"><div><p className="eyebrow">A WALK THROUGH PHOTOGRAPHS</p><h2>한 장씩, 동네 산책.</h2></div><span className="muted small">사진마다 새로운 장면을 만나세요.</span></div><div className="photo-grid">{photos?.items.slice(0,12).map(p=><figure key={p.id}><a className="gallery-image" href={p.url} target="_blank" rel="noopener noreferrer" aria-label={`${p.title} 원본 사진 새 탭에서 보기`}><PhotoImage src={p.url} alt={p.title} sizes="(max-width:700px) 50vw, 25vw"/></a><figcaption><strong>{p.title}</strong><span>© {p.photographer||p.source}</span><span>{p.month} · 공공누리 1유형</span></figcaption></figure>)}</div>{!photos?.items.length&&<p className="empty-inline">사진을 준비하고 있어요.</p>}</section>
 <section id="quiet" className="wrap detail-section quiet-section"><div><p className="eyebrow"><CalendarDays size={15}/> TIMING MAKES A DIFFERENCE</p><h2>조금 더 여유로운 날.</h2><p>{region.anchorPlace}의 관광지 집중률 예측이에요.<br/>숫자가 낮은 날을 골라 천천히 둘러보세요.</p><span className="source-note">상대적 집중률이며 실제 방문객 수가 아닙니다.<br/>당일 현장 상황과 다를 수 있어요.</span></div><div>{forecasts.length?<><div className="calendar-grid">{forecasts.map(d=><div key={`${d.baseYmd}-${d.tAtsNm}`} className={`calendar-cell ${Number(d.cnctrRate)===min?"quietest":""}`}><span>{d.baseYmd.slice(4,6)}.{d.baseYmd.slice(6)}</span><strong>{Number(d.cnctrRate).toFixed(1)}</strong></div>)}</div><p className="muted small">진한 초록: 조회 기간 중 가장 낮은 집중률 · 한국관광공사</p></>:<div className="empty-inline"><CalendarDays size={28}/><p>이 관광지의 예측 정보가 아직 없어요.<br/>사진과 주변 장소를 먼저 둘러보세요.</p></div>}</div></section>
 <section id="data" className="wrap data-note"><Info size={23}/><div><h3>여행의 근거도, 투명하게.</h3><p>현재는 에디터가 선정한 8개 지역의 실제 관광정보를 제공해요. 전국 17개 지표 비교와 숨은 정도 점수는 데이터 검증을 마치면 공개합니다.</p><Link href="/methodology">출처와 선정 방식 살펴보기 <ArrowUpRight size={15}/></Link></div></section></main>;
}
