DROP TABLE IF EXISTS datasets;
DROP TABLE IF EXISTS sync_runs;

ALTER TABLE regions
    MODIFY latitude DOUBLE NULL,
    MODIFY longitude DOUBLE NULL,
    MODIFY anchor_place VARCHAR(100) NULL;

INSERT IGNORE INTO regions (code,name,area_code,area_name,tagline,theme,latitude,longitude,anchor_place) VALUES
('11110','종로구','11','서울특별시','데이터로 만나는 종로구 여행','DISCOVERY',NULL,NULL,NULL),
('11140','중구','11','서울특별시','데이터로 만나는 중구 여행','DISCOVERY',NULL,NULL,NULL),
('11170','용산구','11','서울특별시','데이터로 만나는 용산구 여행','DISCOVERY',NULL,NULL,NULL),
('11200','성동구','11','서울특별시','데이터로 만나는 성동구 여행','DISCOVERY',NULL,NULL,NULL),
('11215','광진구','11','서울특별시','데이터로 만나는 광진구 여행','DISCOVERY',NULL,NULL,NULL),
('11230','동대문구','11','서울특별시','데이터로 만나는 동대문구 여행','DISCOVERY',NULL,NULL,NULL),
('11260','중랑구','11','서울특별시','데이터로 만나는 중랑구 여행','DISCOVERY',NULL,NULL,NULL),
('11290','성북구','11','서울특별시','데이터로 만나는 성북구 여행','DISCOVERY',NULL,NULL,NULL),
('11305','강북구','11','서울특별시','데이터로 만나는 강북구 여행','DISCOVERY',NULL,NULL,NULL),
('11320','도봉구','11','서울특별시','데이터로 만나는 도봉구 여행','DISCOVERY',NULL,NULL,NULL),
('11350','노원구','11','서울특별시','데이터로 만나는 노원구 여행','DISCOVERY',NULL,NULL,NULL),
('11380','은평구','11','서울특별시','데이터로 만나는 은평구 여행','DISCOVERY',NULL,NULL,NULL),
('11410','서대문구','11','서울특별시','데이터로 만나는 서대문구 여행','DISCOVERY',NULL,NULL,NULL),
('11440','마포구','11','서울특별시','데이터로 만나는 마포구 여행','DISCOVERY',NULL,NULL,NULL),
('11470','양천구','11','서울특별시','데이터로 만나는 양천구 여행','DISCOVERY',NULL,NULL,NULL),
('11500','강서구','11','서울특별시','데이터로 만나는 강서구 여행','DISCOVERY',NULL,NULL,NULL),
('11530','구로구','11','서울특별시','데이터로 만나는 구로구 여행','DISCOVERY',NULL,NULL,NULL),
('11545','금천구','11','서울특별시','데이터로 만나는 금천구 여행','DISCOVERY',NULL,NULL,NULL),
('11560','영등포구','11','서울특별시','데이터로 만나는 영등포구 여행','DISCOVERY',NULL,NULL,NULL),
('11590','동작구','11','서울특별시','데이터로 만나는 동작구 여행','DISCOVERY',NULL,NULL,NULL),
('11620','관악구','11','서울특별시','데이터로 만나는 관악구 여행','DISCOVERY',NULL,NULL,NULL),
('11650','서초구','11','서울특별시','데이터로 만나는 서초구 여행','DISCOVERY',NULL,NULL,NULL),
('11680','강남구','11','서울특별시','데이터로 만나는 강남구 여행','DISCOVERY',NULL,NULL,NULL),
('11710','송파구','11','서울특별시','데이터로 만나는 송파구 여행','DISCOVERY',NULL,NULL,NULL),
('11740','강동구','11','서울특별시','데이터로 만나는 강동구 여행','DISCOVERY',NULL,NULL,NULL),
('26110','중구','26','부산광역시','데이터로 만나는 중구 여행','DISCOVERY',NULL,NULL,NULL),
('26140','서구','26','부산광역시','데이터로 만나는 서구 여행','DISCOVERY',NULL,NULL,NULL),
('26170','동구','26','부산광역시','데이터로 만나는 동구 여행','DISCOVERY',NULL,NULL,NULL),
('26200','영도구','26','부산광역시','데이터로 만나는 영도구 여행','DISCOVERY',NULL,NULL,NULL),
('26230','부산진구','26','부산광역시','데이터로 만나는 부산진구 여행','DISCOVERY',NULL,NULL,NULL),
('26260','동래구','26','부산광역시','데이터로 만나는 동래구 여행','DISCOVERY',NULL,NULL,NULL),
('26290','남구','26','부산광역시','데이터로 만나는 남구 여행','DISCOVERY',NULL,NULL,NULL),
('26320','북구','26','부산광역시','데이터로 만나는 북구 여행','DISCOVERY',NULL,NULL,NULL),
('26350','해운대구','26','부산광역시','데이터로 만나는 해운대구 여행','DISCOVERY',NULL,NULL,NULL),
('26380','사하구','26','부산광역시','데이터로 만나는 사하구 여행','DISCOVERY',NULL,NULL,NULL),
('26410','금정구','26','부산광역시','데이터로 만나는 금정구 여행','DISCOVERY',NULL,NULL,NULL),
('26440','강서구','26','부산광역시','데이터로 만나는 강서구 여행','DISCOVERY',NULL,NULL,NULL),
('26470','연제구','26','부산광역시','데이터로 만나는 연제구 여행','DISCOVERY',NULL,NULL,NULL),
('26500','수영구','26','부산광역시','데이터로 만나는 수영구 여행','DISCOVERY',NULL,NULL,NULL),
('26530','사상구','26','부산광역시','데이터로 만나는 사상구 여행','DISCOVERY',NULL,NULL,NULL),
('26710','기장군','26','부산광역시','데이터로 만나는 기장군 여행','DISCOVERY',NULL,NULL,NULL),
('27110','중구','27','대구광역시','데이터로 만나는 중구 여행','DISCOVERY',NULL,NULL,NULL),
('27140','동구','27','대구광역시','데이터로 만나는 동구 여행','DISCOVERY',NULL,NULL,NULL),
('27170','서구','27','대구광역시','데이터로 만나는 서구 여행','DISCOVERY',NULL,NULL,NULL),
('27200','남구','27','대구광역시','데이터로 만나는 남구 여행','DISCOVERY',NULL,NULL,NULL),
('27230','북구','27','대구광역시','데이터로 만나는 북구 여행','DISCOVERY',NULL,NULL,NULL),
('27260','수성구','27','대구광역시','데이터로 만나는 수성구 여행','DISCOVERY',NULL,NULL,NULL),
('27290','달서구','27','대구광역시','데이터로 만나는 달서구 여행','DISCOVERY',NULL,NULL,NULL),
('27710','달성군','27','대구광역시','데이터로 만나는 달성군 여행','DISCOVERY',NULL,NULL,NULL),
('27720','군위군','27','대구광역시','데이터로 만나는 군위군 여행','DISCOVERY',NULL,NULL,NULL),
('28110','중구','28','인천광역시','데이터로 만나는 중구 여행','DISCOVERY',NULL,NULL,NULL),
('28140','동구','28','인천광역시','데이터로 만나는 동구 여행','DISCOVERY',NULL,NULL,NULL),
('28177','미추홀구','28','인천광역시','데이터로 만나는 미추홀구 여행','DISCOVERY',NULL,NULL,NULL),
('28185','연수구','28','인천광역시','데이터로 만나는 연수구 여행','DISCOVERY',NULL,NULL,NULL),
('28200','남동구','28','인천광역시','데이터로 만나는 남동구 여행','DISCOVERY',NULL,NULL,NULL),
('28237','부평구','28','인천광역시','데이터로 만나는 부평구 여행','DISCOVERY',NULL,NULL,NULL),
('28245','계양구','28','인천광역시','데이터로 만나는 계양구 여행','DISCOVERY',NULL,NULL,NULL),
('28260','서구','28','인천광역시','데이터로 만나는 서구 여행','DISCOVERY',NULL,NULL,NULL),
('28710','강화군','28','인천광역시','데이터로 만나는 강화군 여행','DISCOVERY',NULL,NULL,NULL),
('28720','옹진군','28','인천광역시','데이터로 만나는 옹진군 여행','DISCOVERY',NULL,NULL,NULL),
('29110','동구','29','광주광역시','데이터로 만나는 동구 여행','DISCOVERY',NULL,NULL,NULL),
('29140','서구','29','광주광역시','데이터로 만나는 서구 여행','DISCOVERY',NULL,NULL,NULL),
('29155','남구','29','광주광역시','데이터로 만나는 남구 여행','DISCOVERY',NULL,NULL,NULL),
('29170','북구','29','광주광역시','데이터로 만나는 북구 여행','DISCOVERY',NULL,NULL,NULL),
('29200','광산구','29','광주광역시','데이터로 만나는 광산구 여행','DISCOVERY',NULL,NULL,NULL),
('30110','동구','30','대전광역시','데이터로 만나는 동구 여행','DISCOVERY',NULL,NULL,NULL),
('30140','중구','30','대전광역시','데이터로 만나는 중구 여행','DISCOVERY',NULL,NULL,NULL),
('30170','서구','30','대전광역시','데이터로 만나는 서구 여행','DISCOVERY',NULL,NULL,NULL),
('30200','유성구','30','대전광역시','데이터로 만나는 유성구 여행','DISCOVERY',NULL,NULL,NULL),
('30230','대덕구','30','대전광역시','데이터로 만나는 대덕구 여행','DISCOVERY',NULL,NULL,NULL),
('31110','중구','31','울산광역시','데이터로 만나는 중구 여행','DISCOVERY',NULL,NULL,NULL),
('31140','남구','31','울산광역시','데이터로 만나는 남구 여행','DISCOVERY',NULL,NULL,NULL),
('31170','동구','31','울산광역시','데이터로 만나는 동구 여행','DISCOVERY',NULL,NULL,NULL),
('31200','북구','31','울산광역시','데이터로 만나는 북구 여행','DISCOVERY',NULL,NULL,NULL),
('31710','울주군','31','울산광역시','데이터로 만나는 울주군 여행','DISCOVERY',NULL,NULL,NULL),
('36110','세종특별자치시','36','세종특별자치시','데이터로 만나는 세종특별자치시 여행','DISCOVERY',NULL,NULL,NULL),
('41111','수원시 장안구','41','경기도','데이터로 만나는 수원시 장안구 여행','DISCOVERY',NULL,NULL,NULL),
('41113','수원시 권선구','41','경기도','데이터로 만나는 수원시 권선구 여행','DISCOVERY',NULL,NULL,NULL),
('41115','수원시 팔달구','41','경기도','데이터로 만나는 수원시 팔달구 여행','DISCOVERY',NULL,NULL,NULL),
('41117','수원시 영통구','41','경기도','데이터로 만나는 수원시 영통구 여행','DISCOVERY',NULL,NULL,NULL),
('41131','성남시 수정구','41','경기도','데이터로 만나는 성남시 수정구 여행','DISCOVERY',NULL,NULL,NULL),
('41133','성남시 중원구','41','경기도','데이터로 만나는 성남시 중원구 여행','DISCOVERY',NULL,NULL,NULL),
('41135','성남시 분당구','41','경기도','데이터로 만나는 성남시 분당구 여행','DISCOVERY',NULL,NULL,NULL),
('41150','의정부시','41','경기도','데이터로 만나는 의정부시 여행','DISCOVERY',NULL,NULL,NULL),
('41171','안양시 만안구','41','경기도','데이터로 만나는 안양시 만안구 여행','DISCOVERY',NULL,NULL,NULL),
('41173','안양시 동안구','41','경기도','데이터로 만나는 안양시 동안구 여행','DISCOVERY',NULL,NULL,NULL),
('41192','부천시 원미구','41','경기도','데이터로 만나는 부천시 원미구 여행','DISCOVERY',NULL,NULL,NULL),
('41194','부천시 소사구','41','경기도','데이터로 만나는 부천시 소사구 여행','DISCOVERY',NULL,NULL,NULL),
('41196','부천시 오정구','41','경기도','데이터로 만나는 부천시 오정구 여행','DISCOVERY',NULL,NULL,NULL),
('41210','광명시','41','경기도','데이터로 만나는 광명시 여행','DISCOVERY',NULL,NULL,NULL),
('41220','평택시','41','경기도','데이터로 만나는 평택시 여행','DISCOVERY',NULL,NULL,NULL),
('41250','동두천시','41','경기도','데이터로 만나는 동두천시 여행','DISCOVERY',NULL,NULL,NULL),
('41271','안산시 상록구','41','경기도','데이터로 만나는 안산시 상록구 여행','DISCOVERY',NULL,NULL,NULL),
('41273','안산시 단원구','41','경기도','데이터로 만나는 안산시 단원구 여행','DISCOVERY',NULL,NULL,NULL),
('41281','고양시 덕양구','41','경기도','데이터로 만나는 고양시 덕양구 여행','DISCOVERY',NULL,NULL,NULL),
('41285','고양시 일산동구','41','경기도','데이터로 만나는 고양시 일산동구 여행','DISCOVERY',NULL,NULL,NULL),
('41287','고양시 일산서구','41','경기도','데이터로 만나는 고양시 일산서구 여행','DISCOVERY',NULL,NULL,NULL),
('41290','과천시','41','경기도','데이터로 만나는 과천시 여행','DISCOVERY',NULL,NULL,NULL),
('41310','구리시','41','경기도','데이터로 만나는 구리시 여행','DISCOVERY',NULL,NULL,NULL),
('41360','남양주시','41','경기도','데이터로 만나는 남양주시 여행','DISCOVERY',NULL,NULL,NULL),
('41370','오산시','41','경기도','데이터로 만나는 오산시 여행','DISCOVERY',NULL,NULL,NULL),
('41390','시흥시','41','경기도','데이터로 만나는 시흥시 여행','DISCOVERY',NULL,NULL,NULL),
('41410','군포시','41','경기도','데이터로 만나는 군포시 여행','DISCOVERY',NULL,NULL,NULL),
('41430','의왕시','41','경기도','데이터로 만나는 의왕시 여행','DISCOVERY',NULL,NULL,NULL),
('41450','하남시','41','경기도','데이터로 만나는 하남시 여행','DISCOVERY',NULL,NULL,NULL),
('41461','용인시 처인구','41','경기도','데이터로 만나는 용인시 처인구 여행','DISCOVERY',NULL,NULL,NULL),
('41463','용인시 기흥구','41','경기도','데이터로 만나는 용인시 기흥구 여행','DISCOVERY',NULL,NULL,NULL),
('41465','용인시 수지구','41','경기도','데이터로 만나는 용인시 수지구 여행','DISCOVERY',NULL,NULL,NULL),
('41480','파주시','41','경기도','데이터로 만나는 파주시 여행','DISCOVERY',NULL,NULL,NULL),
('41500','이천시','41','경기도','데이터로 만나는 이천시 여행','DISCOVERY',NULL,NULL,NULL),
('41550','안성시','41','경기도','데이터로 만나는 안성시 여행','DISCOVERY',NULL,NULL,NULL),
('41570','김포시','41','경기도','데이터로 만나는 김포시 여행','DISCOVERY',NULL,NULL,NULL),
('41590','화성시','41','경기도','데이터로 만나는 화성시 여행','DISCOVERY',NULL,NULL,NULL),
('41610','광주시','41','경기도','데이터로 만나는 광주시 여행','DISCOVERY',NULL,NULL,NULL),
('41630','양주시','41','경기도','데이터로 만나는 양주시 여행','DISCOVERY',NULL,NULL,NULL),
('41650','포천시','41','경기도','데이터로 만나는 포천시 여행','DISCOVERY',NULL,NULL,NULL),
('41670','여주시','41','경기도','데이터로 만나는 여주시 여행','DISCOVERY',NULL,NULL,NULL),
('41800','연천군','41','경기도','데이터로 만나는 연천군 여행','DISCOVERY',NULL,NULL,NULL),
('41820','가평군','41','경기도','데이터로 만나는 가평군 여행','DISCOVERY',NULL,NULL,NULL),
('41830','양평군','41','경기도','데이터로 만나는 양평군 여행','DISCOVERY',NULL,NULL,NULL),
('43111','청주시 상당구','43','충청북도','데이터로 만나는 청주시 상당구 여행','DISCOVERY',NULL,NULL,NULL),
('43112','청주시 서원구','43','충청북도','데이터로 만나는 청주시 서원구 여행','DISCOVERY',NULL,NULL,NULL),
('43113','청주시 흥덕구','43','충청북도','데이터로 만나는 청주시 흥덕구 여행','DISCOVERY',NULL,NULL,NULL),
('43114','청주시 청원구','43','충청북도','데이터로 만나는 청주시 청원구 여행','DISCOVERY',NULL,NULL,NULL),
('43130','충주시','43','충청북도','데이터로 만나는 충주시 여행','DISCOVERY',NULL,NULL,NULL),
('43150','제천시','43','충청북도','데이터로 만나는 제천시 여행','DISCOVERY',NULL,NULL,NULL),
('43720','보은군','43','충청북도','데이터로 만나는 보은군 여행','DISCOVERY',NULL,NULL,NULL),
('43730','옥천군','43','충청북도','데이터로 만나는 옥천군 여행','DISCOVERY',NULL,NULL,NULL),
('43740','영동군','43','충청북도','데이터로 만나는 영동군 여행','DISCOVERY',NULL,NULL,NULL),
('43745','증평군','43','충청북도','데이터로 만나는 증평군 여행','DISCOVERY',NULL,NULL,NULL),
('43750','진천군','43','충청북도','데이터로 만나는 진천군 여행','DISCOVERY',NULL,NULL,NULL),
('43760','괴산군','43','충청북도','데이터로 만나는 괴산군 여행','DISCOVERY',NULL,NULL,NULL),
('43770','음성군','43','충청북도','데이터로 만나는 음성군 여행','DISCOVERY',NULL,NULL,NULL),
('43800','단양군','43','충청북도','데이터로 만나는 단양군 여행','DISCOVERY',NULL,NULL,NULL),
('44131','천안시 동남구','44','충청남도','데이터로 만나는 천안시 동남구 여행','DISCOVERY',NULL,NULL,NULL),
('44133','천안시 서북구','44','충청남도','데이터로 만나는 천안시 서북구 여행','DISCOVERY',NULL,NULL,NULL),
('44150','공주시','44','충청남도','데이터로 만나는 공주시 여행','DISCOVERY',NULL,NULL,NULL),
('44180','보령시','44','충청남도','데이터로 만나는 보령시 여행','DISCOVERY',NULL,NULL,NULL),
('44200','아산시','44','충청남도','데이터로 만나는 아산시 여행','DISCOVERY',NULL,NULL,NULL),
('44210','서산시','44','충청남도','데이터로 만나는 서산시 여행','DISCOVERY',NULL,NULL,NULL),
('44230','논산시','44','충청남도','데이터로 만나는 논산시 여행','DISCOVERY',NULL,NULL,NULL),
('44250','계룡시','44','충청남도','데이터로 만나는 계룡시 여행','DISCOVERY',NULL,NULL,NULL),
('44270','당진시','44','충청남도','데이터로 만나는 당진시 여행','DISCOVERY',NULL,NULL,NULL),
('44710','금산군','44','충청남도','데이터로 만나는 금산군 여행','DISCOVERY',NULL,NULL,NULL),
('44760','부여군','44','충청남도','데이터로 만나는 부여군 여행','DISCOVERY',NULL,NULL,NULL),
('44770','서천군','44','충청남도','데이터로 만나는 서천군 여행','DISCOVERY',NULL,NULL,NULL),
('44790','청양군','44','충청남도','데이터로 만나는 청양군 여행','DISCOVERY',NULL,NULL,NULL),
('44800','홍성군','44','충청남도','데이터로 만나는 홍성군 여행','DISCOVERY',NULL,NULL,NULL),
('44810','예산군','44','충청남도','데이터로 만나는 예산군 여행','DISCOVERY',NULL,NULL,NULL),
('44825','태안군','44','충청남도','데이터로 만나는 태안군 여행','DISCOVERY',NULL,NULL,NULL),
('46110','목포시','46','전라남도','데이터로 만나는 목포시 여행','DISCOVERY',NULL,NULL,NULL),
('46130','여수시','46','전라남도','데이터로 만나는 여수시 여행','DISCOVERY',NULL,NULL,NULL),
('46150','순천시','46','전라남도','데이터로 만나는 순천시 여행','DISCOVERY',NULL,NULL,NULL),
('46170','나주시','46','전라남도','데이터로 만나는 나주시 여행','DISCOVERY',NULL,NULL,NULL),
('46230','광양시','46','전라남도','데이터로 만나는 광양시 여행','DISCOVERY',NULL,NULL,NULL),
('46710','담양군','46','전라남도','데이터로 만나는 담양군 여행','DISCOVERY',NULL,NULL,NULL),
('46720','곡성군','46','전라남도','데이터로 만나는 곡성군 여행','DISCOVERY',NULL,NULL,NULL),
('46730','구례군','46','전라남도','데이터로 만나는 구례군 여행','DISCOVERY',NULL,NULL,NULL),
('46770','고흥군','46','전라남도','데이터로 만나는 고흥군 여행','DISCOVERY',NULL,NULL,NULL),
('46780','보성군','46','전라남도','데이터로 만나는 보성군 여행','DISCOVERY',NULL,NULL,NULL),
('46790','화순군','46','전라남도','데이터로 만나는 화순군 여행','DISCOVERY',NULL,NULL,NULL),
('46800','장흥군','46','전라남도','데이터로 만나는 장흥군 여행','DISCOVERY',NULL,NULL,NULL),
('46810','강진군','46','전라남도','데이터로 만나는 강진군 여행','DISCOVERY',NULL,NULL,NULL),
('46820','해남군','46','전라남도','데이터로 만나는 해남군 여행','DISCOVERY',NULL,NULL,NULL),
('46830','영암군','46','전라남도','데이터로 만나는 영암군 여행','DISCOVERY',NULL,NULL,NULL),
('46840','무안군','46','전라남도','데이터로 만나는 무안군 여행','DISCOVERY',NULL,NULL,NULL),
('46860','함평군','46','전라남도','데이터로 만나는 함평군 여행','DISCOVERY',NULL,NULL,NULL),
('46870','영광군','46','전라남도','데이터로 만나는 영광군 여행','DISCOVERY',NULL,NULL,NULL),
('46880','장성군','46','전라남도','데이터로 만나는 장성군 여행','DISCOVERY',NULL,NULL,NULL),
('46890','완도군','46','전라남도','데이터로 만나는 완도군 여행','DISCOVERY',NULL,NULL,NULL),
('46900','진도군','46','전라남도','데이터로 만나는 진도군 여행','DISCOVERY',NULL,NULL,NULL),
('46910','신안군','46','전라남도','데이터로 만나는 신안군 여행','DISCOVERY',NULL,NULL,NULL),
('47111','포항시 남구','47','경상북도','데이터로 만나는 포항시 남구 여행','DISCOVERY',NULL,NULL,NULL),
('47113','포항시 북구','47','경상북도','데이터로 만나는 포항시 북구 여행','DISCOVERY',NULL,NULL,NULL),
('47130','경주시','47','경상북도','데이터로 만나는 경주시 여행','DISCOVERY',NULL,NULL,NULL),
('47150','김천시','47','경상북도','데이터로 만나는 김천시 여행','DISCOVERY',NULL,NULL,NULL),
('47170','안동시','47','경상북도','데이터로 만나는 안동시 여행','DISCOVERY',NULL,NULL,NULL),
('47190','구미시','47','경상북도','데이터로 만나는 구미시 여행','DISCOVERY',NULL,NULL,NULL),
('47210','영주시','47','경상북도','데이터로 만나는 영주시 여행','DISCOVERY',NULL,NULL,NULL),
('47230','영천시','47','경상북도','데이터로 만나는 영천시 여행','DISCOVERY',NULL,NULL,NULL),
('47250','상주시','47','경상북도','데이터로 만나는 상주시 여행','DISCOVERY',NULL,NULL,NULL),
('47280','문경시','47','경상북도','데이터로 만나는 문경시 여행','DISCOVERY',NULL,NULL,NULL),
('47290','경산시','47','경상북도','데이터로 만나는 경산시 여행','DISCOVERY',NULL,NULL,NULL),
('47730','의성군','47','경상북도','데이터로 만나는 의성군 여행','DISCOVERY',NULL,NULL,NULL),
('47750','청송군','47','경상북도','데이터로 만나는 청송군 여행','DISCOVERY',NULL,NULL,NULL),
('47760','영양군','47','경상북도','데이터로 만나는 영양군 여행','DISCOVERY',NULL,NULL,NULL),
('47770','영덕군','47','경상북도','데이터로 만나는 영덕군 여행','DISCOVERY',NULL,NULL,NULL),
('47820','청도군','47','경상북도','데이터로 만나는 청도군 여행','DISCOVERY',NULL,NULL,NULL),
('47830','고령군','47','경상북도','데이터로 만나는 고령군 여행','DISCOVERY',NULL,NULL,NULL),
('47840','성주군','47','경상북도','데이터로 만나는 성주군 여행','DISCOVERY',NULL,NULL,NULL),
('47850','칠곡군','47','경상북도','데이터로 만나는 칠곡군 여행','DISCOVERY',NULL,NULL,NULL),
('47900','예천군','47','경상북도','데이터로 만나는 예천군 여행','DISCOVERY',NULL,NULL,NULL),
('47920','봉화군','47','경상북도','데이터로 만나는 봉화군 여행','DISCOVERY',NULL,NULL,NULL),
('47930','울진군','47','경상북도','데이터로 만나는 울진군 여행','DISCOVERY',NULL,NULL,NULL),
('47940','울릉군','47','경상북도','데이터로 만나는 울릉군 여행','DISCOVERY',NULL,NULL,NULL),
('48121','창원시 의창구','48','경상남도','데이터로 만나는 창원시 의창구 여행','DISCOVERY',NULL,NULL,NULL),
('48123','창원시 성산구','48','경상남도','데이터로 만나는 창원시 성산구 여행','DISCOVERY',NULL,NULL,NULL),
('48125','창원시 마산합포구','48','경상남도','데이터로 만나는 창원시 마산합포구 여행','DISCOVERY',NULL,NULL,NULL),
('48127','창원시 마산회원구','48','경상남도','데이터로 만나는 창원시 마산회원구 여행','DISCOVERY',NULL,NULL,NULL),
('48129','창원시 진해구','48','경상남도','데이터로 만나는 창원시 진해구 여행','DISCOVERY',NULL,NULL,NULL),
('48170','진주시','48','경상남도','데이터로 만나는 진주시 여행','DISCOVERY',NULL,NULL,NULL),
('48220','통영시','48','경상남도','데이터로 만나는 통영시 여행','DISCOVERY',NULL,NULL,NULL),
('48240','사천시','48','경상남도','데이터로 만나는 사천시 여행','DISCOVERY',NULL,NULL,NULL),
('48250','김해시','48','경상남도','데이터로 만나는 김해시 여행','DISCOVERY',NULL,NULL,NULL),
('48270','밀양시','48','경상남도','데이터로 만나는 밀양시 여행','DISCOVERY',NULL,NULL,NULL),
('48310','거제시','48','경상남도','데이터로 만나는 거제시 여행','DISCOVERY',NULL,NULL,NULL),
('48330','양산시','48','경상남도','데이터로 만나는 양산시 여행','DISCOVERY',NULL,NULL,NULL),
('48720','의령군','48','경상남도','데이터로 만나는 의령군 여행','DISCOVERY',NULL,NULL,NULL),
('48730','함안군','48','경상남도','데이터로 만나는 함안군 여행','DISCOVERY',NULL,NULL,NULL),
('48740','창녕군','48','경상남도','데이터로 만나는 창녕군 여행','DISCOVERY',NULL,NULL,NULL),
('48820','고성군','48','경상남도','데이터로 만나는 고성군 여행','DISCOVERY',NULL,NULL,NULL),
('48840','남해군','48','경상남도','데이터로 만나는 남해군 여행','DISCOVERY',NULL,NULL,NULL),
('48850','하동군','48','경상남도','데이터로 만나는 하동군 여행','DISCOVERY',NULL,NULL,NULL),
('48860','산청군','48','경상남도','데이터로 만나는 산청군 여행','DISCOVERY',NULL,NULL,NULL),
('48870','함양군','48','경상남도','데이터로 만나는 함양군 여행','DISCOVERY',NULL,NULL,NULL),
('48880','거창군','48','경상남도','데이터로 만나는 거창군 여행','DISCOVERY',NULL,NULL,NULL),
('48890','합천군','48','경상남도','데이터로 만나는 합천군 여행','DISCOVERY',NULL,NULL,NULL),
('50110','제주시','50','제주특별자치도','데이터로 만나는 제주시 여행','DISCOVERY',NULL,NULL,NULL),
('50130','서귀포시','50','제주특별자치도','데이터로 만나는 서귀포시 여행','DISCOVERY',NULL,NULL,NULL),
('51110','춘천시','51','강원특별자치도','데이터로 만나는 춘천시 여행','DISCOVERY',NULL,NULL,NULL),
('51130','원주시','51','강원특별자치도','데이터로 만나는 원주시 여행','DISCOVERY',NULL,NULL,NULL),
('51150','강릉시','51','강원특별자치도','데이터로 만나는 강릉시 여행','DISCOVERY',NULL,NULL,NULL),
('51170','동해시','51','강원특별자치도','데이터로 만나는 동해시 여행','DISCOVERY',NULL,NULL,NULL),
('51190','태백시','51','강원특별자치도','데이터로 만나는 태백시 여행','DISCOVERY',NULL,NULL,NULL),
('51210','속초시','51','강원특별자치도','데이터로 만나는 속초시 여행','DISCOVERY',NULL,NULL,NULL),
('51230','삼척시','51','강원특별자치도','데이터로 만나는 삼척시 여행','DISCOVERY',NULL,NULL,NULL),
('51720','홍천군','51','강원특별자치도','데이터로 만나는 홍천군 여행','DISCOVERY',NULL,NULL,NULL),
('51730','횡성군','51','강원특별자치도','데이터로 만나는 횡성군 여행','DISCOVERY',NULL,NULL,NULL),
('51750','영월군','51','강원특별자치도','데이터로 만나는 영월군 여행','DISCOVERY',NULL,NULL,NULL),
('51760','평창군','51','강원특별자치도','데이터로 만나는 평창군 여행','DISCOVERY',NULL,NULL,NULL),
('51770','정선군','51','강원특별자치도','데이터로 만나는 정선군 여행','DISCOVERY',NULL,NULL,NULL),
('51780','철원군','51','강원특별자치도','데이터로 만나는 철원군 여행','DISCOVERY',NULL,NULL,NULL),
('51790','화천군','51','강원특별자치도','데이터로 만나는 화천군 여행','DISCOVERY',NULL,NULL,NULL),
('51800','양구군','51','강원특별자치도','데이터로 만나는 양구군 여행','DISCOVERY',NULL,NULL,NULL),
('51810','인제군','51','강원특별자치도','데이터로 만나는 인제군 여행','DISCOVERY',NULL,NULL,NULL),
('51820','고성군','51','강원특별자치도','데이터로 만나는 고성군 여행','DISCOVERY',NULL,NULL,NULL),
('51830','양양군','51','강원특별자치도','데이터로 만나는 양양군 여행','DISCOVERY',NULL,NULL,NULL),
('52111','전주시 완산구','52','전북특별자치도','데이터로 만나는 전주시 완산구 여행','DISCOVERY',NULL,NULL,NULL),
('52113','전주시 덕진구','52','전북특별자치도','데이터로 만나는 전주시 덕진구 여행','DISCOVERY',NULL,NULL,NULL),
('52130','군산시','52','전북특별자치도','데이터로 만나는 군산시 여행','DISCOVERY',NULL,NULL,NULL),
('52140','익산시','52','전북특별자치도','데이터로 만나는 익산시 여행','DISCOVERY',NULL,NULL,NULL),
('52180','정읍시','52','전북특별자치도','데이터로 만나는 정읍시 여행','DISCOVERY',NULL,NULL,NULL),
('52190','남원시','52','전북특별자치도','데이터로 만나는 남원시 여행','DISCOVERY',NULL,NULL,NULL),
('52210','김제시','52','전북특별자치도','데이터로 만나는 김제시 여행','DISCOVERY',NULL,NULL,NULL),
('52710','완주군','52','전북특별자치도','데이터로 만나는 완주군 여행','DISCOVERY',NULL,NULL,NULL),
('52720','진안군','52','전북특별자치도','데이터로 만나는 진안군 여행','DISCOVERY',NULL,NULL,NULL),
('52730','무주군','52','전북특별자치도','데이터로 만나는 무주군 여행','DISCOVERY',NULL,NULL,NULL),
('52740','장수군','52','전북특별자치도','데이터로 만나는 장수군 여행','DISCOVERY',NULL,NULL,NULL),
('52750','임실군','52','전북특별자치도','데이터로 만나는 임실군 여행','DISCOVERY',NULL,NULL,NULL),
('52770','순창군','52','전북특별자치도','데이터로 만나는 순창군 여행','DISCOVERY',NULL,NULL,NULL),
('52790','고창군','52','전북특별자치도','데이터로 만나는 고창군 여행','DISCOVERY',NULL,NULL,NULL),
('52800','부안군','52','전북특별자치도','데이터로 만나는 부안군 여행','DISCOVERY',NULL,NULL,NULL);
