import Link from "next/link";
import {api} from "@/lib/api";
export const metadata={title:"다시봄 이야기와 데이터 출처"};
type Status={mode:string;persistentPublicData:boolean;regionCount:number;featuredRegionCount:number};
export default async function Methodology(){
 const status=await api<Status>("/data-status");
 return <main id="main" className="wrap page-main story"><p className="eyebrow">OUR WAY OF DISCOVERING</p><h1 className="page-title">모든 동네에는,<br/>다시 볼 이유가 있어요.</h1><p className="story-lead">다시봄은 익숙한 여행지 너머로 시선을 옮깁니다.<br/>공공 API를 실시간으로 호출해 지금 확인할 수 있는 여행정보를 보여드립니다.</p>
 <section><span className="story-index">01</span><div><h2>오늘의 다시봄 동네</h2><p>인구감소·관심 또는 반값여행 지역 중 한국관광공사 관광사진 수상작이 있는 곳을 후보로 만듭니다. 최신 제공일의 시군구 방문량이 낮을수록 숨은 점수를 높게 계산하고, 비교 지역 중 방문량이 하위 절반인 후보를 한국 날짜에 따라 순환합니다. 방문량 자료가 없으면 사진 기준 소개임을 알립니다. 후보 수와 방문량 기준일도 API 응답에 함께 공개합니다.</p></div></section>
 <section><span className="story-index">02</span><div><h2>화면에서 바로 호출하는 공공 API</h2><p>관광사진 수상작·사진갤러리, 방문자, 관광 자원 수요, 국문 관광정보와 관광지 집중률 API를 서버에서 직접 호출합니다. 공공 API 응답은 서비스 DB에 저장하거나 장기 캐싱하지 않습니다. MySQL은 {status?.regionCount??252}개 공식 지역 코드와 익명 좋아요 같은 서비스 자체 데이터에만 사용합니다.</p><p className="source-note">연동 방식: {status?.mode??"LIVE"} · 공공 API 영구 저장: {status?.persistentPublicData?"사용":"미사용"}</p><a href="https://www.data.go.kr/data/15101914/openapi.do" target="_blank" rel="noopener noreferrer">관광사진 데이터 원문 ↗</a><br/><a href="https://www.data.go.kr/data/15101578/openapi.do" target="_blank" rel="noopener noreferrer">국문 관광정보 원문 ↗</a><br/><a href="https://www.data.go.kr/data/15152138/openapi.do" target="_blank" rel="noopener noreferrer">관광 자원 수요 데이터 원문 ↗</a></div></section>
 <section><span className="story-index">03</span><div><h2>17개 지표와 빈 결과 원칙</h2><p>관광 서비스 수요 12개와 문화자원 수요 5개를 표시합니다. 자연·힐링·미식·문화·숙박·체험에 해당하는 지표를 6개 축으로 묶으며, 쇼핑·운송 지표는 개별 수치로 표시합니다. 이 값은 관광 수요이며 여행지의 품질 점수가 아닙니다. 최근 12개월을 제한된 시간 안에 조회하고 최신 제공월을 선택하며, 원천 API가 빈 결과를 반환하면 임의 장소나 점수를 만들지 않고 대기 상태를 그대로 알립니다.</p><p>집중률은 API가 지원하는 관광지만 향후 30일 히트맵으로 표시하며 실제 방문객 수가 아닌 상대 예측값입니다.</p></div></section>
 <section><span className="story-index">04</span><div><h2>전국 지도와 정책 필터</h2><p>행정안전부 기준 인구감소지역 89곳과 관심지역 18곳, 대한민국 구석구석의 현재 반값여행 25곳을 필터로 제공합니다. 지도는 서비스의 252개 지역 코드와 일치하는 2025년 12월 경계를 사용합니다. 현재 행정구역 구분과 다를 수 있으며, 방문량의 일대일 변경 코드는 연결하고 자료가 없는 지역은 회색으로 구분합니다. 경계 출처는 통계청 SGIS·vuski/admdongkor(CC BY 4.0)입니다.</p><a href="https://www.mois.go.kr/frt/sub/a06/b06/populationDecline/screen.do" target="_blank" rel="noopener noreferrer">행정안전부 지정 현황 ↗</a><br/><a href="https://korean.visitkorea.or.kr/dgtourcard/tour50.do" target="_blank" rel="noopener noreferrer">반값여행 참여지역 ↗</a></div></section>
 <section><span className="story-index">05</span><div><h2>출처와 개인정보</h2><p>관광정보 출처: ⓒ한국관광공사<br/>관광사진 출처: ⓒ한국관광콘텐츠랩</p><p>여행 저장은 브라우저 로컬 저장소를 사용합니다. 좋아요 중복 방지를 위해 개인정보를 포함하지 않는 무작위 쿠키를 사용하며, 사용자의 GPS나 현재 위치를 수집하거나 서버로 전송하지 않습니다.</p></div></section><Link className="button" href="/explore">전국 지역 둘러보기 ↗</Link></main>;
}
